# Generated by Django 4.2.2 on 2024-12-16 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50, verbose_name="Место")),
                ("time", models.DateTimeField(verbose_name="Время выполнения")),
                ("duration", models.IntegerField(verbose_name="Время на выполнение")),
                (
                    "periodicity",
                    models.SmallIntegerField(default=1, verbose_name="Периодичность"),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                (
                    "started_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата начала привычки",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
